Fix bug (related to #1333): RTE in --diagnostics with LC_ALL=C
* getlocale() returns (None, None) causing join() to throw this RTE:
  TypeError: sequence item 0: expected str instance, NoneType found